name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run go test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run leetcode Tests
        run: |
          go test leetcode/*.go -v